/** Starter list offered by "Varsayılan listeyi yükle"; codes follow ISCO-08 minor groups. */
export const DEFAULT_OCCUPATIONS: ReadonlyArray<{ code: string; name: string }> = [
  { code: '1120', name: 'Genel Müdür / Yönetici' },
  { code: '1321', name: 'İmalat Yöneticisi' },
  { code: '2141', name: 'Endüstri Mühendisi' },
  { code: '2142', name: 'İnşaat Mühendisi' },
  { code: '2144', name: 'Makine Mühendisi' },
  { code: '2151', name: 'Elektrik Mühendisi' },
  { code: '2263', name: 'İş Sağlığı ve Güvenliği Uzmanı' },
  { code: '3112', name: 'İnşaat Teknikeri' },
  { code: '3115', name: 'Makine Teknikeri' },
  { code: '3122', name: 'İmalat Ustabaşı' },
  { code: '3123', name: 'İnşaat Ustabaşı' },
  { code: '4110', name: 'Büro Elemanı' },
  { code: '4321', name: 'Depo Görevlisi' },
  { code: '5120', name: 'Aşçı' },
  { code: '5131', name: 'Garson' },
  { code: '5223', name: 'Satış Elemanı' },
  { code: '5414', name: 'Güvenlik Görevlisi' },
  { code: '7115', name: 'Marangoz' },
  { code: '7119', name: 'İnşaat İşçisi' },
  { code: '7123', name: 'Sıvacı / Alçıpan Ustası' },
  { code: '7126', name: 'Tesisatçı' },
  { code: '7131', name: 'Boyacı' },
  { code: '7212', name: 'Kaynakçı' },
  { code: '7213', name: 'Sac İşçisi' },
  { code: '7223', name: 'Tornacı / Talaşlı İmalat Operatörü' },
  { code: '7231', name: 'Motorlu Taşıt Tamircisi' },
  { code: '7411', name: 'Elektrikçi' },
  { code: '7412', name: 'Elektromekanik Teknisyeni' },
  { code: '7533', name: 'Dikiş Makinesi Operatörü' },
  { code: '8111', name: 'Maden İşçisi' },
  { code: '8121', name: 'Metal İşleme Tesisi Operatörü' },
  { code: '8131', name: 'Kimyasal Ürün Tesisi Operatörü' },
  { code: '8142', name: 'Plastik Ürün Makinesi Operatörü' },
  { code: '8152', name: 'Dokuma Makinesi Operatörü' },
  { code: '8160', name: 'Gıda Üretim Makinesi Operatörü' },
  { code: '8322', name: 'Şoför (Otomobil / Hafif Ticari)' },
  { code: '8332', name: 'Kamyon / Ağır Vasıta Şoförü' },
  { code: '8343', name: 'Vinç Operatörü' },
  { code: '8344', name: 'Forklift Operatörü' },
  { code: '9112', name: 'Temizlik Görevlisi' },
  { code: '9313', name: 'İnşaat Yardımcı İşçisi' },
  { code: '9329', name: 'İmalat Yardımcı İşçisi' },
  { code: '9333', name: 'Yükleme / Boşaltma İşçisi' },
];
