/**
 * The visit plan that ties the demo together: every protocol, its ordered items and the
 * examination (Ek-2 report) outcome. Test modules and documents reference these keys.
 */
import type { $Enums } from '../../src/generated/prisma/client';
import { uid } from './lib';

export type ItemState = 'DONE' | 'PENDING' | 'CANCELLED';

export interface ExamPlan {
  status: $Enums.ExaminationStatus;
  decision: $Enums.FitnessDecision;
  physician: 'demir' | 'aksoy' | 'koc';
  restrictions?: string;
  findings?: string;
  conclusion?: string;
  nextDueMonths?: number;
  anamnesis: Record<string, unknown>;
  systems?: Record<string, { status: 'NORMAL' | 'ABNORMAL' | 'NOT_EXAMINED'; note?: string }>;
  /** Measurement values keyed by MEASUREMENT key. */
  measurements: Record<string, number>;
}

export interface ProtocolPlan {
  key: string;
  employee: string;
  year: number;
  sequence: number;
  type: $Enums.ExaminationType;
  status: $Enums.ProtocolStatus;
  daysAgo: number;
  hour?: number;
  items: Partial<Record<$Enums.ProtocolItemType, ItemState>>;
  openedBy: 'nurse' | 'clerk' | 'admin';
  closedBy?: 'physician' | 'radiologist' | 'admin';
  notes?: string;
  exam?: ExamPlan;
}

export const protocolId = (key: string) => uid(`protocol:${key}`);
export const examinationId = (key: string) => uid(`exam:${key}`);

const NORMAL_SYSTEMS = Object.fromEntries(
  [
    'HEAD_NECK',
    'EYES',
    'ENT',
    'RESPIRATORY',
    'CARDIOVASCULAR',
    'GASTROINTESTINAL',
    'GENITOURINARY',
    'MUSCULOSKELETAL',
    'NEUROLOGICAL',
    'SKIN',
    'PSYCHIATRIC',
    'ENDOCRINE',
  ].map((k) => [k, { status: 'NORMAL' as const }]),
);

const systems = (overrides: ExamPlan['systems'] = {}) => ({ ...NORMAL_SYSTEMS, ...overrides });

export const PROTOCOLS: ProtocolPlan[] = [
  // ------------------------------------------------------------------ 2024
  {
    key: 'p24-1',
    employee: 'mehmet-kaya',
    year: 2024,
    sequence: 1,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 610,
    items: {
      RADIOLOGY: 'DONE',
      SPIROMETRY: 'DONE',
      AUDIOMETRY: 'DONE',
      PNEUMOCONIOSIS: 'DONE',
      HEALTH_REPORT: 'DONE',
    },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'Yıllık periyodik - tozlu ortam paketi; bazal odyometri ve SFT.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Genel durum iyi. Solunum sesleri doğal. PA grafi ve ILO okuması negatif.',
      conclusion: 'Kaynak işinde çalışmasında sakınca yoktur.',
      anamnesis: {
        complaints: 'Yok',
        pastIllnesses: 'Yok',
        surgeries: 'Apandektomi (2001)',
        familyHistory: 'Baba: hipertansiyon',
        medications: 'Yok',
        allergies: 'Penisilin',
        smoking: 'NEVER',
        alcohol: 'NONE',
        occupationalHistory: '2010–2016 Gebze Metal (kaynakçı), 2016– Demir Çelik',
        exposures: ['DUST', 'NOISE', 'HEAT_COLD', 'CHEMICAL'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 178,
        WEIGHT: 80,
        WAIST: 92,
        SYSTOLIC: 122,
        DIASTOLIC: 78,
        PULSE: 72,
        SPO2: 98,
        FEV1: 96,
        FVC: 98,
        FEV1_FVC: 82,
        HEARING_RIGHT: 14,
        HEARING_LEFT: 15,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
        GLUCOSE: 88,
        HEMOGLOBIN: 15.1,
        TOTAL_CHOLESTEROL: 178,
      },
    },
  },
  {
    key: 'p24-2',
    employee: 'ayse-yilmaz',
    year: 2024,
    sequence: 2,
    type: 'PRE_EMPLOYMENT',
    status: 'COMPLETED',
    daysAgo: 570,
    items: {
      RADIOLOGY: 'DONE',
      AUDIOMETRY: 'DONE',
      ECG: 'DONE',
      SPIROMETRY: 'DONE',
      EYE: 'DONE',
      LAB: 'DONE',
      HEALTH_REPORT: 'DONE',
    },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'İşe giriş standart paket.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'koc',
      nextDueMonths: 12,
      findings: 'Sistem muayeneleri doğal.',
      conclusion: 'CNC operatörü olarak çalışabilir.',
      anamnesis: {
        complaints: 'Yok',
        pastIllnesses: 'Yok',
        smoking: 'NEVER',
        alcohol: 'OCCASIONAL',
        exposures: ['NOISE', 'CHEMICAL'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 164,
        WEIGHT: 56,
        SYSTOLIC: 110,
        DIASTOLIC: 70,
        PULSE: 76,
        SPO2: 99,
        HEARING_RIGHT: 9,
        HEARING_LEFT: 10,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
        GLUCOSE: 84,
        HEMOGLOBIN: 12.9,
      },
    },
  },
  {
    key: 'p24-3',
    employee: 'hasan-demir',
    year: 2024,
    sequence: 3,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 545,
    items: { EYE: 'DONE', ECG: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'nurse',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Kan basıncı sınırda yüksek. Gözlükle görme tam.',
      conclusion: 'Forklift kullanımına uygundur; gözlük zorunlu.',
      anamnesis: {
        complaints: 'Ara sıra baş ağrısı',
        pastIllnesses: 'Hipertansiyon (2023)',
        medications: 'Amlodipin 5 mg',
        smoking: 'FORMER',
        packYears: 10,
        alcohol: 'OCCASIONAL',
        exposures: ['VIBRATION', 'SHIFT_WORK'],
      },
      systems: systems({
        CARDIOVASCULAR: { status: 'ABNORMAL', note: 'TA 142/92 mmHg' },
        EYES: { status: 'ABNORMAL', note: 'Miyopi, gözlük kullanıyor' },
      }),
      measurements: {
        HEIGHT: 172,
        WEIGHT: 93,
        WAIST: 104,
        SYSTOLIC: 142,
        DIASTOLIC: 92,
        PULSE: 80,
        SPO2: 97,
        VISION_RIGHT: 0.4,
        VISION_LEFT: 0.5,
        GLUCOSE: 104,
        HEMOGLOBIN: 15.6,
        TOTAL_CHOLESTEROL: 228,
      },
    },
  },
  // ------------------------------------------------------------------ 2025
  {
    key: 'p25-1',
    employee: 'mehmet-kaya',
    year: 2025,
    sequence: 1,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 300,
    items: { SPIROMETRY: 'DONE', AUDIOMETRY: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'nurse',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'FEV1 bazale göre hafif düşüş. Kilo artışı.',
      conclusion: 'Çalışabilir; solunum koruyucu kullanımı denetlenmeli.',
      anamnesis: {
        complaints: 'Sabahları hafif öksürük',
        smoking: 'NEVER',
        alcohol: 'NONE',
        exposures: ['DUST', 'NOISE', 'HEAT_COLD'],
      },
      systems: systems({ RESPIRATORY: { status: 'NORMAL', note: 'Ral yok' } }),
      measurements: {
        HEIGHT: 178,
        WEIGHT: 83,
        WAIST: 96,
        SYSTOLIC: 126,
        DIASTOLIC: 82,
        PULSE: 74,
        SPO2: 97,
        FEV1: 90,
        FVC: 94,
        FEV1_FVC: 80,
        HEARING_RIGHT: 16,
        HEARING_LEFT: 18,
        GLUCOSE: 92,
        HEMOGLOBIN: 15.3,
        TOTAL_CHOLESTEROL: 190,
      },
    },
  },
  {
    key: 'p25-2',
    employee: 'fatma-sahin',
    year: 2025,
    sequence: 2,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 280,
    items: { SPIROMETRY: 'DONE', LAB: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT_WITH_RESTRICTIONS',
      physician: 'demir',
      nextDueMonths: 6,
      restrictions:
        'Solvent maruziyeti olan kapalı boya kabininde çalışamaz; yalnızca havalandırmalı alanda, tam yüz maske ile.',
      findings: 'SFT obstrüktif patern, bronkodilatöre yanıt pozitif. Sigara 15 paket-yıl.',
      conclusion: 'Astım açısından göğüs hastalıkları konsültasyonu istendi.',
      anamnesis: {
        complaints: 'Efor dispnesi, hırıltı',
        pastIllnesses: 'Çocuklukta bronşit',
        smoking: 'CURRENT',
        packYears: 15,
        alcohol: 'NONE',
        exposures: ['CHEMICAL', 'DUST'],
      },
      systems: systems({
        RESPIRATORY: { status: 'ABNORMAL', note: 'Ekspiryum uzun, yaygın ronküs' },
      }),
      measurements: {
        HEIGHT: 160,
        WEIGHT: 62,
        SYSTOLIC: 118,
        DIASTOLIC: 76,
        PULSE: 84,
        SPO2: 95,
        FEV1: 62,
        FVC: 85,
        FEV1_FVC: 61,
        GLUCOSE: 90,
        HEMOGLOBIN: 12.4,
      },
    },
  },
  {
    key: 'p25-3',
    employee: 'ibrahim-aydin',
    year: 2025,
    sequence: 3,
    type: 'EXIT',
    status: 'COMPLETED',
    daysAgo: 200,
    items: { HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    notes: 'İşten ayrılış muayenesi.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      findings: 'Mesleki hastalık bulgusu yok.',
      conclusion: 'İşten ayrılış muayenesi tamamlandı; meslek hastalığı şüphesi yok.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'CURRENT',
        packYears: 20,
        alcohol: 'OCCASIONAL',
        exposures: ['VIBRATION', 'SHIFT_WORK'],
      },
      systems: systems(),
      measurements: { HEIGHT: 176, WEIGHT: 88, SYSTOLIC: 130, DIASTOLIC: 84, PULSE: 78, SPO2: 97 },
    },
  },
  {
    key: 'p25-4',
    employee: 'hasan-demir',
    year: 2025,
    sequence: 4,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 180,
    items: { ECG: 'DONE', EYE: 'DONE', RADIOLOGY: 'CANCELLED', LAB: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'Lomber grafi hasta talebiyle iptal edildi.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT_WITH_RESTRICTIONS',
      physician: 'demir',
      nextDueMonths: 6,
      restrictions:
        'Gece vardiyasında çalışamaz. Kan basıncı kontrol altına alınana kadar 3 ayda bir hekim kontrolü.',
      findings: 'EKG: sol ventrikül hipertrofisi ve ST depresyonu. TA 150/95.',
      conclusion:
        'Kardiyoloji konsültasyonu istendi; forklift kullanımı kontrol sonrası yeniden değerlendirilecek.',
      anamnesis: {
        complaints: 'Çarpıntı',
        pastIllnesses: 'Hipertansiyon',
        medications: 'Amlodipin 10 mg',
        smoking: 'FORMER',
        packYears: 10,
        alcohol: 'OCCASIONAL',
        exposures: ['VIBRATION', 'SHIFT_WORK'],
      },
      systems: systems({
        CARDIOVASCULAR: { status: 'ABNORMAL', note: 'TA 150/95, S4 duyuldu' },
        EYES: { status: 'ABNORMAL', note: 'Gözlükle tam' },
        ENDOCRINE: { status: 'ABNORMAL', note: 'BKİ 32 - obezite' },
      }),
      measurements: {
        HEIGHT: 172,
        WEIGHT: 96,
        WAIST: 108,
        SYSTOLIC: 150,
        DIASTOLIC: 95,
        PULSE: 82,
        SPO2: 96,
        VISION_RIGHT: 0.4,
        VISION_LEFT: 0.5,
        GLUCOSE: 112,
        HEMOGLOBIN: 15.8,
        TOTAL_CHOLESTEROL: 241,
      },
    },
  },
  {
    key: 'p25-5',
    employee: 'osman-yildirim',
    year: 2025,
    sequence: 5,
    type: 'PRE_EMPLOYMENT',
    status: 'COMPLETED',
    daysAgo: 250,
    items: { RADIOLOGY: 'DONE', SPIROMETRY: 'DONE', PNEUMOCONIOSIS: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'koc',
      nextDueMonths: 12,
      findings: 'SFT kısıtlayıcı patern (obezite ile uyumlu). Grafi ILO negatif.',
      conclusion: 'Ahşap işlemede çalışabilir; kilo verme önerildi.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'NONE',
        exposures: ['DUST', 'NOISE'],
      },
      systems: systems({ ENDOCRINE: { status: 'ABNORMAL', note: 'BKİ 30.4' } }),
      measurements: {
        HEIGHT: 174,
        WEIGHT: 92,
        WAIST: 106,
        SYSTOLIC: 128,
        DIASTOLIC: 84,
        PULSE: 76,
        SPO2: 97,
        FEV1: 66,
        FVC: 62,
        FEV1_FVC: 87,
      },
    },
  },
  {
    key: 'p25-6',
    employee: 'ramazan-gunes',
    year: 2025,
    sequence: 6,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 150,
    items: { ECG: 'DONE', EYE: 'DONE', AUDIOMETRY: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'Şoför periyodik - sürücü sağlık kriterleri.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Sinüs bradikardisi (52/dk) - sporcu kalbi ile uyumlu, semptomsuz.',
      conclusion: 'Ağır vasıta sürücülüğüne uygundur.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'NONE',
        exposures: ['VIBRATION', 'SHIFT_WORK'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 174,
        WEIGHT: 70,
        WAIST: 84,
        SYSTOLIC: 116,
        DIASTOLIC: 72,
        PULSE: 52,
        SPO2: 99,
        HEARING_RIGHT: 12,
        HEARING_LEFT: 14,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
        GLUCOSE: 82,
        TOTAL_CHOLESTEROL: 165,
      },
    },
  },
  {
    key: 'p25-7',
    employee: 'nur-simsek',
    year: 2025,
    sequence: 7,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 120,
    items: { LAB: 'DONE', RADIOLOGY: 'CANCELLED', HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    notes: 'Portör paketi; PA grafi 6 ay önce çekildiği için iptal.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 6,
      findings: 'Portör tetkikleri negatif, HBsAg negatif.',
      conclusion: 'Gıda ile temas eden işte çalışabilir.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'NONE',
        exposures: ['HEAT_COLD', 'BIOLOGICAL'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 161,
        WEIGHT: 68,
        SYSTOLIC: 120,
        DIASTOLIC: 78,
        PULSE: 74,
        SPO2: 98,
        GLUCOSE: 96,
        HEMOGLOBIN: 11.8,
      },
    },
  },
  // ------------------------------------------------------------------ 2026
  {
    key: 'p26-1',
    employee: 'mehmet-kaya',
    year: 2026,
    sequence: 1,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 20,
    items: {
      RADIOLOGY: 'DONE',
      SPIROMETRY: 'DONE',
      AUDIOMETRY: 'DONE',
      PNEUMOCONIOSIS: 'DONE',
      ECG: 'DONE',
      HEALTH_REPORT: 'DONE',
    },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'Tozlu ortam paketi + EKG. A/B okuyucu ILO değerlendirmesi.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT_WITH_RESTRICTIONS',
      physician: 'demir',
      nextDueMonths: 6,
      restrictions:
        'Gürültü >85 dB(A) alanlarda çift koruyucu (tıkaç + kulaklık) zorunlu. Silika tozu maruziyeti olan kabin içi taşlama işinde çalışamaz.',
      findings:
        'Odyometride 3-6 kHz çentik ve bazale göre eşik kayması (STS). SFT: FEV1 bazale göre %16 düşüş. ILO okuması 1/0 p/q (A okuyucu), 0/1 (B okuyucu) - sınırda.',
      conclusion:
        'Pnömokonyoz ön tanısı ile meslek hastalıkları hastanesine sevk; 6 ay sonra kontrol.',
      anamnesis: {
        complaints: 'Kulak çınlaması, eforla nefes darlığı',
        pastIllnesses: 'Yok',
        surgeries: 'Apandektomi (2001)',
        familyHistory: 'Baba: hipertansiyon',
        medications: 'Yok',
        allergies: 'Penisilin',
        smoking: 'NEVER',
        alcohol: 'NONE',
        occupationalHistory: '2010–2016 Gebze Metal (kaynakçı), 2016– Demir Çelik',
        exposures: ['DUST', 'NOISE', 'HEAT_COLD', 'CHEMICAL'],
      },
      systems: systems({
        RESPIRATORY: { status: 'ABNORMAL', note: 'Bazallerde ince raller' },
        ENT: { status: 'ABNORMAL', note: 'Bilateral sensörinöral kayıp' },
      }),
      measurements: {
        HEIGHT: 178,
        WEIGHT: 84,
        WAIST: 98,
        SYSTOLIC: 128,
        DIASTOLIC: 84,
        PULSE: 76,
        SPO2: 96,
        FEV1: 81,
        FVC: 90,
        FEV1_FVC: 76,
        HEARING_RIGHT: 21,
        HEARING_LEFT: 24,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 0.9,
        GLUCOSE: 95,
        HEMOGLOBIN: 15.0,
        TOTAL_CHOLESTEROL: 196,
      },
    },
  },
  {
    key: 'p26-2',
    employee: 'ayse-yilmaz',
    year: 2026,
    sequence: 2,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 25,
    items: { AUDIOMETRY: 'DONE', EYE: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'Gürültülü ortam paketi.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Odyometri bazale göre değişiklik yok. Görme tam.',
      conclusion: 'Çalışmasında sakınca yoktur.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'OCCASIONAL',
        exposures: ['NOISE', 'CHEMICAL'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 164,
        WEIGHT: 58,
        SYSTOLIC: 112,
        DIASTOLIC: 72,
        PULSE: 70,
        SPO2: 99,
        HEARING_RIGHT: 10,
        HEARING_LEFT: 11,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
      },
    },
  },
  {
    key: 'p26-3',
    employee: 'huseyin-dogan',
    year: 2026,
    sequence: 3,
    type: 'RETURN_TO_WORK',
    status: 'COMPLETED',
    daysAgo: 30,
    items: {
      RADIOLOGY: 'DONE',
      SPIROMETRY: 'DONE',
      ECG: 'DONE',
      AUDIOMETRY: 'DONE',
      EYE: 'DONE',
      PNEUMOCONIOSIS: 'DONE',
      HEALTH_REPORT: 'DONE',
    },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: '45 gün istirahat sonrası işe dönüş (KOAH alevlenmesi).',
    exam: {
      status: 'APPROVED',
      decision: 'UNFIT',
      physician: 'demir',
      nextDueMonths: 3,
      findings:
        'Ağır obstrüktif patern (FEV1 %38). EKG: sağ dal bloğu, T negatifliği. Görme alanı sol üst kadranda defekt. Grafide amfizem ve bül.',
      conclusion:
        'Kaynak işinde çalışması uygun değildir. Toz ve dumandan uzak, hafif işe yönlendirilmesi; göğüs hastalıkları ve kardiyoloji takibi önerilir.',
      anamnesis: {
        complaints: 'İstirahatte nefes darlığı, balgam',
        pastIllnesses: 'KOAH (2022), hipertansiyon',
        medications: 'Tiotropium, salbutamol, ramipril',
        smoking: 'FORMER',
        packYears: 35,
        alcohol: 'NONE',
        occupationalHistory: '1990– kaynakçı (çeşitli işyerleri)',
        exposures: ['DUST', 'NOISE', 'HEAT_COLD', 'CHEMICAL'],
      },
      systems: systems({
        RESPIRATORY: { status: 'ABNORMAL', note: 'Fıçı göğüs, ekspiryum belirgin uzun, ronküs' },
        CARDIOVASCULAR: { status: 'ABNORMAL', note: 'TA 138/88' },
        EYES: { status: 'ABNORMAL', note: 'Konfrontasyonda sol üst kadran defekti' },
        ENT: { status: 'ABNORMAL', note: 'Orta derece işitme kaybı' },
      }),
      measurements: {
        HEIGHT: 168,
        WEIGHT: 64,
        WAIST: 88,
        SYSTOLIC: 138,
        DIASTOLIC: 88,
        PULSE: 104,
        SPO2: 91,
        FEV1: 38,
        FVC: 71,
        FEV1_FVC: 42,
        HEARING_RIGHT: 46,
        HEARING_LEFT: 49,
        VISION_RIGHT: 0.8,
        VISION_LEFT: 0.7,
      },
    },
  },
  {
    key: 'p26-4',
    employee: 'ali-ozturk',
    year: 2026,
    sequence: 4,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 12,
    items: {
      ECG: 'DONE',
      AUDIOMETRY: 'DONE',
      SPIROMETRY: 'DONE',
      EYE: 'DONE',
      HEALTH_REPORT: 'DONE',
    },
    openedBy: 'clerk',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'EKG: inkomplet sağ dal bloğu (normal varyant). Diğer tetkikler normal.',
      conclusion: 'Çalışabilir.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'OCCASIONAL',
        exposures: ['NOISE', 'ERGONOMIC', 'HEIGHT'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 175,
        WEIGHT: 79,
        WAIST: 90,
        SYSTOLIC: 120,
        DIASTOLIC: 80,
        PULSE: 66,
        SPO2: 98,
        FEV1: 98,
        FVC: 101,
        FEV1_FVC: 80,
        HEARING_RIGHT: 11,
        HEARING_LEFT: 12,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
        GLUCOSE: 89,
        HEMOGLOBIN: 15.4,
        TOTAL_CHOLESTEROL: 182,
      },
    },
  },
  {
    key: 'p26-5',
    employee: 'elif-koc',
    year: 2026,
    sequence: 5,
    type: 'PRE_EMPLOYMENT',
    status: 'COMPLETED',
    daysAgo: 10,
    items: {
      RADIOLOGY: 'DONE',
      AUDIOMETRY: 'DONE',
      ECG: 'DONE',
      SPIROMETRY: 'DONE',
      EYE: 'DONE',
      LAB: 'DONE',
      HEALTH_REPORT: 'DONE',
    },
    openedBy: 'clerk',
    closedBy: 'physician',
    notes: 'İşe giriş standart paket - vernik bölümü.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Tüm tetkikler normal sınırlarda.',
      conclusion: 'Vernik bölümünde çalışabilir; KKD kullanımı eğitimi verildi.',
      anamnesis: {
        complaints: 'Yok',
        allergies: 'Polen',
        smoking: 'NEVER',
        alcohol: 'NONE',
        exposures: ['CHEMICAL', 'DUST'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 165,
        WEIGHT: 60,
        WAIST: 74,
        SYSTOLIC: 108,
        DIASTOLIC: 68,
        PULSE: 72,
        SPO2: 99,
        FEV1: 97,
        FVC: 99,
        FEV1_FVC: 84,
        HEARING_RIGHT: 8,
        HEARING_LEFT: 9,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
        GLUCOSE: 86,
        HEMOGLOBIN: 13.2,
        TOTAL_CHOLESTEROL: 170,
      },
    },
  },
  {
    key: 'p26-6',
    employee: 'can-aksoy',
    year: 2026,
    sequence: 6,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 8,
    items: { EYE: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    notes: 'Ofis paketi - ekranlı araç.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 24,
      findings: 'Miyopi; gözlükle tam görme.',
      conclusion: 'Ekranlı araç kullanımına uygundur; gözlük reçetesi güncellenmeli.',
      anamnesis: {
        complaints: 'Akşamları göz yorgunluğu',
        smoking: 'NEVER',
        alcohol: 'OCCASIONAL',
        exposures: ['DISPLAY_SCREEN'],
      },
      systems: systems({ EYES: { status: 'ABNORMAL', note: 'Miyopi -2.50 / -2.00' } }),
      measurements: {
        HEIGHT: 183,
        WEIGHT: 76,
        SYSTOLIC: 118,
        DIASTOLIC: 74,
        PULSE: 68,
        SPO2: 99,
        VISION_RIGHT: 0.3,
        VISION_LEFT: 0.4,
      },
    },
  },
  {
    key: 'p26-7',
    employee: 'mustafa-arslan',
    year: 2026,
    sequence: 7,
    type: 'PERIODIC',
    status: 'IN_PROGRESS',
    daysAgo: 3,
    items: { EYE: 'DONE', AUDIOMETRY: 'DONE', RADIOLOGY: 'PENDING', HEALTH_REPORT: 'PENDING' },
    openedBy: 'nurse',
    notes: 'Radyoloji raporu bekleniyor.',
    exam: {
      status: 'IN_PROGRESS',
      decision: 'PENDING',
      physician: 'demir',
      findings: 'Renk görme kusuru (Ishihara 6/14). Sol kulakta hafif kayıp.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'CURRENT',
        packYears: 12,
        alcohol: 'NONE',
        exposures: ['HEIGHT', 'NOISE'],
      },
      systems: systems({ EYES: { status: 'ABNORMAL', note: 'Renk görme kusuru' } }),
      measurements: {
        HEIGHT: 170,
        WEIGHT: 77,
        SYSTOLIC: 124,
        DIASTOLIC: 80,
        PULSE: 74,
        SPO2: 97,
        HEARING_RIGHT: 15,
        HEARING_LEFT: 29,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
      },
    },
  },
  {
    key: 'p26-8',
    employee: 'emine-celik',
    year: 2026,
    sequence: 8,
    type: 'PRE_EMPLOYMENT',
    status: 'IN_PROGRESS',
    daysAgo: 1,
    items: { ECG: 'DONE', LAB: 'PENDING', EYE: 'PENDING', HEALTH_REPORT: 'PENDING' },
    openedBy: 'clerk',
    notes: 'Depo işe giriş; laboratuvar sonucu bekleniyor.',
    exam: {
      status: 'IN_PROGRESS',
      decision: 'PENDING',
      physician: 'demir',
      anamnesis: { complaints: 'Yok', smoking: 'NEVER', alcohol: 'NONE', exposures: ['ERGONOMIC'] },
      measurements: { HEIGHT: 167, WEIGHT: 61, SYSTOLIC: 110, DIASTOLIC: 70, PULSE: 78, SPO2: 99 },
    },
  },
  {
    key: 'p26-9',
    employee: 'burak-erdogan',
    year: 2026,
    sequence: 9,
    type: 'PERIODIC',
    status: 'CANCELLED',
    daysAgo: 5,
    items: { AUDIOMETRY: 'CANCELLED', EYE: 'CANCELLED', HEALTH_REPORT: 'CANCELLED' },
    openedBy: 'clerk',
    closedBy: 'admin',
    notes: 'Çalışan randevuya gelmedi; işveren yeni tarih talep edecek.',
    exam: {
      status: 'CANCELLED',
      decision: 'PENDING',
      physician: 'demir',
      anamnesis: {},
      measurements: {},
    },
  },
  {
    key: 'p26-10',
    employee: 'ahmet-polat',
    year: 2026,
    sequence: 10,
    type: 'PRE_EMPLOYMENT',
    status: 'OPEN',
    daysAgo: 0,
    hour: 8,
    items: {
      RADIOLOGY: 'PENDING',
      AUDIOMETRY: 'PENDING',
      ECG: 'PENDING',
      SPIROMETRY: 'PENDING',
      EYE: 'PENDING',
      LAB: 'PENDING',
      HEALTH_REPORT: 'PENDING',
    },
    openedBy: 'clerk',
    notes: 'İşe giriş standart paket; yarın 09:30 muayene.',
    exam: {
      status: 'SCHEDULED',
      decision: 'PENDING',
      physician: 'demir',
      anamnesis: {},
      measurements: {},
    },
  },
  {
    key: 'p26-11',
    employee: 'mahmut-kilinc',
    year: 2026,
    sequence: 11,
    type: 'SPECIAL',
    status: 'OPEN',
    daysAgo: 0,
    hour: 9,
    items: { EYE: 'PENDING', HEALTH_REPORT: 'PENDING' },
    openedBy: 'clerk',
    notes: 'Bireysel başvuru - sürücü belgesi sağlık raporu.',
  },
  {
    key: 'p26-12',
    employee: 'kerem-uslu',
    year: 2026,
    sequence: 12,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 40,
    items: { ECG: 'DONE', AUDIOMETRY: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'nurse',
    closedBy: 'physician',
    notes: 'Gece vardiyası periyodik.',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Normal.',
      conclusion: 'Gece çalışmasına uygundur.',
      anamnesis: {
        complaints: 'Uyku düzensizliği',
        smoking: 'CURRENT',
        packYears: 18,
        alcohol: 'NONE',
        exposures: ['SHIFT_WORK'],
      },
      systems: systems({ ENDOCRINE: { status: 'ABNORMAL', note: 'BKİ 28' } }),
      measurements: {
        HEIGHT: 180,
        WEIGHT: 91,
        WAIST: 100,
        SYSTOLIC: 132,
        DIASTOLIC: 86,
        PULSE: 70,
        SPO2: 97,
        HEARING_RIGHT: 13,
        HEARING_LEFT: 14,
        GLUCOSE: 101,
        TOTAL_CHOLESTEROL: 214,
      },
    },
  },
  {
    key: 'p26-13',
    employee: 'serkan-bulut',
    year: 2026,
    sequence: 13,
    type: 'PERIODIC',
    status: 'IN_PROGRESS',
    daysAgo: 2,
    items: { SPIROMETRY: 'DONE', RADIOLOGY: 'PENDING', HEALTH_REPORT: 'PENDING' },
    openedBy: 'nurse',
    notes: 'PA grafi için randevu verildi.',
    exam: {
      status: 'IN_PROGRESS',
      decision: 'PENDING',
      physician: 'demir',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'OCCASIONAL',
        exposures: ['ERGONOMIC', 'DUST'],
      },
      measurements: {
        HEIGHT: 176,
        WEIGHT: 82,
        SYSTOLIC: 122,
        DIASTOLIC: 78,
        PULSE: 72,
        SPO2: 98,
        FEV1: 95,
        FVC: 97,
        FEV1_FVC: 81,
      },
    },
  },
  {
    key: 'p26-14',
    employee: 'yusuf-kilic',
    year: 2026,
    sequence: 14,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 15,
    items: { EYE: 'DONE', AUDIOMETRY: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 12,
      findings: 'Normal.',
      conclusion: 'Forklift kullanımına uygundur.',
      anamnesis: {
        complaints: 'Yok',
        smoking: 'NEVER',
        alcohol: 'NONE',
        exposures: ['VIBRATION', 'NOISE'],
      },
      systems: systems(),
      measurements: {
        HEIGHT: 179,
        WEIGHT: 83,
        SYSTOLIC: 120,
        DIASTOLIC: 78,
        PULSE: 68,
        SPO2: 98,
        HEARING_RIGHT: 10,
        HEARING_LEFT: 12,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
      },
    },
  },
  {
    key: 'p26-15',
    employee: 'deniz-kara',
    year: 2026,
    sequence: 15,
    type: 'PERIODIC',
    status: 'COMPLETED',
    daysAgo: 60,
    items: { EYE: 'DONE', HEALTH_REPORT: 'DONE' },
    openedBy: 'clerk',
    closedBy: 'physician',
    exam: {
      status: 'APPROVED',
      decision: 'FIT',
      physician: 'demir',
      nextDueMonths: 24,
      findings: 'Presbiyopi başlangıcı (yakın J3).',
      conclusion: 'Ekranlı araç kullanımına uygundur; yakın gözlüğü önerildi.',
      anamnesis: {
        complaints: 'Yakını görmede zorluk',
        smoking: 'NEVER',
        alcohol: 'OCCASIONAL',
        exposures: ['DISPLAY_SCREEN'],
      },
      systems: systems({ EYES: { status: 'ABNORMAL', note: 'Presbiyopi' } }),
      measurements: {
        HEIGHT: 166,
        WEIGHT: 63,
        SYSTOLIC: 114,
        DIASTOLIC: 74,
        PULSE: 72,
        SPO2: 99,
        VISION_RIGHT: 1.0,
        VISION_LEFT: 1.0,
      },
    },
  },
];

export function protocolPlan(key: string): ProtocolPlan {
  const plan = PROTOCOLS.find((p) => p.key === key);
  if (!plan) throw new Error(`Unknown demo protocol ${key}`);
  return plan;
}
